FEAT: Multi Turn + SQL-to-Text
100suping/sql-helper pull request #20
Opened 2024-11-20 12:48 UTC by pakyeon

### 제목
- FEAT: Multi Turn + SQL-to-Text
### 설명
- 멀티턴을 활용한 추가 질문 구현
- SQL-to-Text 구현
- SQL 쿼리 검증 단계 구현
- RAG 개선
### 변경 내용
- 쿼리 생성 함수 수정
- 랭그래프 노드 구성 변
- 벡터 DB에 들어가는 데이터 수정
### 테스트 방법
- `cd sql-helper`
- `sh langgraph.sh`
- `python -m langgraph_.langgraph_main\
    --recursion-limit 50\
    --thread-id "TEST_RUN"\
    --model-name "gpt-4o-mini"\
    --user-question "전체 주문 중 환불된 주문의 비율은 얼마인가요?"\
    --max-query-fix 1`
### 관련 이슈
- 추가 질문 무한 반복
- 쿼리 생성 시 환각 현상 발생

2024-11-21 08:36 UTC, joonavel commented
Conflict 해결해 주세요

2024-11-21 08:42 UTC, joonavel commented on langgraph_/task.py
> +    while True:
이 부분이 질문 분석 루프의 시작점으로 보입니다.
시간을 내서 개선해보도록 하겠습니다.

2024-11-21 08:45 UTC, joonavel commented on langgraph_/task.py
> +                반환 형식:
with_structured_output() 메소드를 사용하기에 반환 형식까지 구태여 추가할 필요는 없습니다

2024-11-21 08:47 UTC, joonavel requested changes
Doctring이 잘 되어 있어 보기 편했습니다.
Conflict 해결하시면, 바로 승인 드리겠습니다.

2024-11-21 08:49 UTC, pakyeon commented
@joonavel Conflict 해결했습니다.

2024-11-21 10:38 UTC, joonavel approved these changes

2024-11-23 11:32 UTC, chloeche22 approved these changes
고생하셨습니다

2024-11-23 14:40 UTC, gabi0215 approved these changes
고생많으셨습니다

2024-11-23 16:49 UTC, won7527 approved these changes
좋습니다!

2024-11-24 08:31 UTC, merged